run:
  timeout: 5m
  go: '1.21'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - goconst
    - gocyclo
    - misspell
    - unparam
    - unconvert
    - prealloc
    - exportloopref
    - nolintlint
    - revive
    - gosec
    - bodyclose
    - rowserrcheck
    - sqlclosecheck
    - nilerr
    - nilnil
    - tenv
    - wastedassign

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        arguments: [checkPrivateReceivers, sayRepetitiveInsteadOfStutters]

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
    # Exclude unsafe usage warnings for arena allocator (expected)
    - path: ".*\\.go"
      text: "Use of unsafe calls should be audited"
      linters:
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
